### ISSUE TITLE
main page - navigation arrow

### ISSUE THREAD

**Issue by LuizaAK** [dwayned84/formy#18]
1. software v. 1.1.1
2. Mozilla v. 50
3. go to www.google.com
3. the arrow icon is upside down in the header
![arrow](https://user-images.githubusercontent.com/81632625/113100564-61f3b300-921d-11eb-8b44-3b3b65f8d280.jpg)

**Comment by dwayned84** [comment]
What browser have you used? 
You forgot to attach screenshot. Please do. 
Don't forget to assign responsible person. In this case it was me.

**Comment by LuizaAK** [comment]
1. go to www.google.com 1.1.1
2. Mozilla Firefox v 50
3.  The arrow is upside down in the header line.
![main page](https://user-images.githubusercontent.com/81632625/113089435-75951e80-9209-11eb-840c-fd588eb3f30e.png)

**Comment by dwayned84** [comment]
Software version - 1.1.1.
Browser - Mozilla v. 50
1. Go to www.google.com 

The developer needs to know software version and browser version first, then he goes to the url you specified as the issue can be related to a certain version of the software or browser only. Moreover, there's a possibility a developer does not have such version of the browser and he will try to reproduce the issue in his browser of another version, which is wrong.

**Comment by dwayned84** [comment]
Great!!!, i'm closing the ticket.
