### ISSUE TITLE
Ошибка на дополнительной вкладке браузера

### ISSUE THREAD

**Issue by AzizbekA** [dwayned84/formy#28]
1. Браузер Mozilla Firefox 50.0
2. Открыть дополнительную вкладку для браузера
3. Лишняя скобка/смайлик после «Untitled»
![5D5267E1-985B-4C6C-B648-47362F31D246](https://user-images.githubusercontent.com/81632638/113080896-7c1b9a00-91f9-11eb-9d4e-15f1bb3e87d7.jpeg)

**Comment by dwayned84** [comment]
Браузер это не наш софт, мы к нему не имеем отношения
