### ISSUE TITLE
Главная страница: Ошибка в дизайне софта-1

### ISSUE THREAD

**Issue by AzizbekA** [dwayned84/formy#31]
1. Браузер Mozilla Firefox 50.0
2. Версия софта Google 1.1.1
3. Перейти на www.google.com
4. Ошибка в написании ссылки «Hopping» где одно «p» лишнее

![435AFC53-1C0A-49F9-A16E-E26547B64654](https://user-images.githubusercontent.com/81632638/113082462-52b03d80-91fc-11eb-8cb7-4f46309f9f97.jpeg)

**Comment by dwayned84** [comment]
Если честно я даже не знаю что такое hoping, если там даже и неправильное написание
