### ISSUE TITLE
Main page - Pipes issue

### ISSUE THREAD

**Issue by LuizaAK** [dwayned84/formy#39]
1. Mozilla Firefox v 50
2. software 1.1.1
3. go to google.com
3. The 'iGoogle' and 'Search settings' are divided by double pipe, while 'Search settings' and 'Sign in' buttons are divided by a single pipe.
![main page (3)_LI](https://user-images.githubusercontent.com/81632625/113095105-b6466500-9214-11eb-880b-b45093bc23e2.jpg)

**Comment by dwayned84** [comment]
Great formatting of the ticket. Just what doctor prescribed. closing the ticket for now.
