### ISSUE TITLE
browser issue - minimize icon

### ISSUE THREAD

**Issue by LuizaAK** [dwayned84/formy#42]
1. Mozilla Firefox v. 50
3. go to www.google.com
3. The 'minimize' icon is half displayed.
![minimize](https://user-images.githubusercontent.com/81632625/113096181-8f892e00-9216-11eb-8681-3ec495b2344b.jpg)

**Comment by dwayned84** [comment]
Browser issue. we work for Google.

**Comment by LuizaAK** [comment]
Do you mean I have to remove the software version from the list?

**Comment by dwayned84** [comment]
No, you should not have reported this ticket in the first place, as it has nothing to do with our software we develop. You have reported the issue on third-party software

**Comment by LuizaAK** [comment]
I'm completely lost. So, what should I do with this bug?

**Comment by dwayned84** [comment]
Nothing)), I will close the ticket.
