### ISSUE TITLE
[Главная страница] Ошибка в названии новой вкладки

### ISSUE THREAD

**Issue by Zaimova** [dwayned84/formy#43]
Браузер Mozilla v.50
Софт v.1.1.1
1. Открываем Mozilla Firefox
2. Открываем новую вкладку
3. Ошибка в названии Title - лишняя закрывающая скобка

![Дефект №2](https://user-images.githubusercontent.com/81632531/113093107-0fac9500-9211-11eb-9f5d-af896cfe1a70.jpg)

**Comment by dwayned84** [comment]
Оформление супер
Тикет закрываю и вешаю на тебя
