### ISSUE TITLE
[Главная страница] Ссылка на раздел NEWS

### ISSUE THREAD

**Issue by Zaimova** [dwayned84/formy#44]
Браузер Mozilla v.50
Софт v.1.1.1
Открываем Mozilla Firefox
Вводим в URL www.google.com
Ссылка на раздел NEWS расположена не на одном уровне с другими ссылками на разделы
![Дефект №3](https://user-images.githubusercontent.com/81632531/113093349-8a75b000-9211-11eb-98f1-86b1ad2a1692.jpg)

**Comment by dwayned84** [comment]
Супер. Молодец. Оформление класс. Закрываю тикет
