### ISSUE TITLE
[Главная страница] Ссылка на раздел MORE

### ISSUE THREAD

**Issue by Zaimova** [dwayned84/formy#45]
Браузер Mozilla v.50
Софт v.1.1.1

Открываем Mozilla Firefox
Вводим в URL www.google.com
Название ссылки на раздел More написано с строчной буквы
![Дефект №4](https://user-images.githubusercontent.com/81632531/113093519-e0e2ee80-9211-11eb-8008-34b1e32cd542.jpg)

**Comment by dwayned84** [comment]
Супер. Я бы еще отметил в этом же тикете что стрелка должна смотреть вниз а не вверх, а так классно. закрываю тикет
