### ISSUE TITLE
[Главная страница] Рамка блока поискового запроса

### ISSUE THREAD

**Issue by Zaimova** [dwayned84/formy#46]
Браузер Mozilla v.50
Софт v.1.1.1
Открываем Mozilla Firefox
Вводим в URL www.google.com
Рамка блока поискового запроса не имеет левой границы
![Дефект №5](https://user-images.githubusercontent.com/81632531/113093642-22739980-9212-11eb-9220-2785671e6e98.jpg)

**Comment by dwayned84** [comment]
Отлично. Закрываю тикет
