### ISSUE TITLE
[Главная страница] Кнопка закрытия окна

### ISSUE THREAD

**Issue by Zaimova** [dwayned84/formy#48]
Браузер Mozilla v.50
Софт v.1.1.1
Открываем Mozilla Firefox
Открываем новую вкладку
Крест на кнопке закрытия окна неполностью прорисован
![Дефект №6](https://user-images.githubusercontent.com/81632531/113094326-45527d80-9213-11eb-952a-9ee2d2687086.jpg)

**Comment by dwayned84** [comment]
Это проблема браузера мы не работаем в Мозилле, мы работаем в гугл. Тикет закрываю
