### ISSUE TITLE
[Главная страница] Дубляж надписи Done

### ISSUE THREAD

**Issue by Zaimova** [dwayned84/formy#49]
Браузер Mozilla v.50
Софт v.1.1.1
Открываем Mozilla Firefox
Вводим в URL www.google.com
В левом нижнем углу надпись Done задублирована

![Дефект №7](https://user-images.githubusercontent.com/81632531/113094866-489a3900-9214-11eb-96ea-55e653f3681b.jpg)

**Comment by dwayned84** [comment]
Ошибка браузера не софта. Закрываю тикет
