### ISSUE TITLE
[Главная страница] Кнопка изменения языка поиска

### ISSUE THREAD

**Issue by Zaimova** [dwayned84/formy#50]
Браузер Mozilla v.50
Софт v.1.1.1
Открываем Mozilla Firefox
Вводим в URL www.google.com
Ошибка в кнопке изменения языка
![Дефект №8](https://user-images.githubusercontent.com/81632531/113094985-8008e580-9214-11eb-8d5f-c26df694be12.jpg)

**Comment by dwayned84** [comment]
Молодец, все супер, только это не кнопка а ссылка. Закрываю тикет и вешаю на тебя
