### ISSUE TITLE
Главная страница : Проблема с горизонтальной разделительной полосой

### ISSUE THREAD

**Issue by cherniihach** [dwayned84/formy#51]
1. Browser Mozilla v.50
2. Soft v.1.1.1
3. Переходим по ссылке : [www.google.com](url)
4. Горизонтальная разделительная полоса под ссылкой "Google" имеет пробел
![test1](https://user-images.githubusercontent.com/31152037/113113911-9c188100-922c-11eb-98a3-7f6d4938455a.JPG)

**Comment by dwayned84** [comment]
Оформление хорошее. Не проставляйте лейблы без разрешения или без знания. 
Название тикета не пойдет. Человек который заглянул посмотреть какие тикеты есть уже по названию должен понимать он ответственен или кто-то другой. и не забывайте назначать ответсвенного человека за тикет, тикет не должен висеть без хозяина
