### ISSUE TITLE
Главная страница баг №1

### ISSUE THREAD

**Issue by cherniihach** [dwayned84/formy#54]
1. Browser Mozilla v.50
2. Soft v.1.1.1
3. Переходим по ссылке : [www.google.com](url)
4. Нету целого ряда кнопок таких как : Обновить страницу, вернутся назад, вернутся вперёд.

**Comment by dwayned84** [comment]
Где нет таких кнопок, у нашего софта нет такого функционала, а мы работает в гугл а не в мозиле, а это проблема браузера. Название тикета плохое, надо кратко описать проблему, не назначили ответственного, бездумно проставили лейблы

**Comment by cherniihach** [comment]
Спасибо за поправку, можно увидеть исправленный пример если не сложно,
заранее спасибо.

ср, 31 мар. 2021 г., 18:55 dwayned84 ***@***.***>:

**Comment by cherniihach** [comment]
Можно оформить пример пример в "github"

ср, 31 мар. 2021 г., 19:07 hi all ***@***.***>:

**Comment by dwayned84** [comment]
Возьмем ваш тикет например озаглавим его так:
Главная страница - проблема с кнопками перехода. 
а вот уже в теле тикета все ок, только не забывайте добавлять скриншот и на скриншоте показывать то место где проблема
Но как я и сказал этот функционал принадлежит браузеру а на вебсайту, поэтому этот тикет по идее нужно закрывать

**Comment by cherniihach** [comment]
Ок, спс.

ср, 31 мар. 2021 г. в 20:05, dwayned84 ***@***.***>:
