### ISSUE TITLE
[Main page] Кнопка поиска Google

### ISSUE THREAD

**Issue by BegimaiB** [dwayned84/formy#56]
Браузер Mozilla v 50
Soft v 1.1.1
1. Открываем Mozilla Firefox
2. Вводить в URL www.google.com
3. Надпись на кнопке "Google Search" лишняя буква O
![image](https://user-images.githubusercontent.com/44816041/113117380-30381780-9230-11eb-8bd1-3901918ac900.png)

**Comment by dwayned84** [comment]
Оформление класс. Молодец. Закрываю тикет
