### ISSUE TITLE
[Main page] Ошибка на кнопке Мне повезет

### ISSUE THREAD

**Issue by BegimaiB** [dwayned84/formy#57]
Браузер Mozilla v 50
Soft v 1.1.1
1. Открываем Mozilla Firefox
2. Вводить в URL www.google.com
3. Ошибка на кнопке "I'm Feeling Unlucky"
4. Должно быть "I'm Feeling Lucky"
![image](https://user-images.githubusercontent.com/44816041/113118284-1e0aa900-9231-11eb-9f0f-84fdbdb42919.png)

**Comment by dwayned84** [comment]
Оформление класс. закрываю тикет
