### ISSUE TITLE
[Main page] Дублирование слова Done

### ISSUE THREAD

**Issue by BegimaiB** [dwayned84/formy#58]
Браузер Mozilla v 50
Soft v 1.1.1
1. Открываем Mozilla Firefox
2. Вводить в URL www.google.com
3. Слово Done внизу с левой стороны написана два раза
![image](https://user-images.githubusercontent.com/44816041/113119300-1bf51a00-9232-11eb-82a5-1f4a110ef82a.png)

**Comment by dwayned84** [comment]
Проблема браузера, мы работает в Гугл
