### ISSUE TITLE
[Main page] Дублирование полосы прокрутки вниз

### ISSUE THREAD

**Issue by BegimaiB** [dwayned84/formy#59]
Браузер Mozilla v 50
Soft v 1.1.1
1. Открываем Mozilla Firefox
2. Вводить в URL www.google.com
3. Знак прокрутки вниз продублирован
![image](https://user-images.githubusercontent.com/44816041/113119801-a89fd800-9232-11eb-9f4f-25422a466d4a.png)

**Comment by dwayned84** [comment]
проблема браузера
