### ISSUE TITLE
[Main page] Неправильное расположение кнопки выпадающего списка more

### ISSUE THREAD

**Issue by BegimaiB** [dwayned84/formy#60]
Браузер Mozilla v 50
Soft v 1.1.1
1. Открываем Mozilla Firefox
2. Вводить в URL www.google.com
3. Кнопка выпадающего списка у more расположено вверх
4. Кнопка должно смотреть вниз
![image](https://user-images.githubusercontent.com/44816041/113121002-008b0e80-9234-11eb-8d7a-85328457e68d.png)

**Comment by dwayned84** [comment]
Отлично. тикет закрываю
