### ISSUE TITLE
Главная страница - проблема с расположением ссылки

### ISSUE THREAD

**Issue by BakAnar** [dwayned84/formy#64]
1.  Браузер Mozilla Firefox v 50.0
2. Google soft v 1.1.1.
3. Перейти на страницу www.google.com
4. Ссылка News расположена выше чем другие ссылки
![InkedGoogle test_LI](https://user-images.githubusercontent.com/81632622/113187911-37384780-927b-11eb-96ca-3773c2197166.jpg)

**Comment by dwayned84** [comment]
@Bakyt-qa Молодец, оформление все как надо, тикет закрываю
