### ISSUE TITLE
Главная страница - проблема с расположением строки поиска браузера

### ISSUE THREAD

**Issue by BakAnar** [dwayned84/formy#65]
1.	Браузер Mozilla Firefox v 50.0
2.	Google soft v 1.1.1.
3.	Перейти на страницу www.google.com
4.	Строка поиска браузера недорисовано и не выравнено по центру.
![InkedGoogle test_LI_1](https://user-images.githubusercontent.com/81632622/113193194-81242c00-9281-11eb-98b2-ba376276e74b.jpg)

**Comment by dwayned84** [comment]
@Bakyt-qa Отлично, оформлено все как надо, тикет закрываю
