### ISSUE TITLE
Главная страница - проблема скрольной кнопки браузера

### ISSUE THREAD

**Issue by BakAnar** [dwayned84/formy#66]
1.	Браузер Mozilla Firefox v 50.0
2.	Google soft v 1.1.1.
3.	Перейти на страницу www.google.com
4.	Скрольная кнопка  главной страницы с указателем вниз размещена дважды.
![InkedGoogle test_LI_2](https://user-images.githubusercontent.com/81632622/113194712-3a373600-9283-11eb-8b7d-a246c128ce68.jpg)

**Comment by dwayned84** [comment]
@Bakyt-qa Мы как тестировщики работает в Гугл, а браузер это продукт другой компании - Мозилла, нам без разницы какие у них дефекты, мы репортим только наши. Тикет закрываю
